<a href="https://colab.research.google.com/github/Srishhtee/PCS221/blob/main/Assignment_1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Q1. Create a data file using Python random module (20000 × 10000).

In [3]:
import numpy as np

rows, cols = 20000, 10000

chunk_size = 1000

with open("large_data.csv", "w") as f:
    for i in range(0, rows, chunk_size):
        data = np.random.rand(min(chunk_size, rows - i), cols)
        np.savetxt(f, data, delimiter=",")

print("Data file created successfully.")

Data file created successfully.


### Q2. Write a program to assign subsequent rows to matrix first row elements.

In [4]:
import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

first_row = matrix[0]

result = {}

for i in range(1, len(matrix)):
    result[f"Row_{i}"] = dict(zip(first_row, matrix[i]))

print(result)

{'Row_1': {np.int64(1): np.int64(4), np.int64(2): np.int64(5), np.int64(3): np.int64(6)}, 'Row_2': {np.int64(1): np.int64(7), np.int64(2): np.int64(8), np.int64(3): np.int64(9)}}


### Q3. Write a program to group similar elements into matrix.

In [5]:
from collections import defaultdict

arr = [1,2,2,3,3,3,4,4]

grouped = defaultdict(list)

for i, val in enumerate(arr):
    grouped[val].append(i)

print(dict(grouped))

{1: [0], 2: [1, 2], 3: [3, 4, 5], 4: [6, 7]}


### Q4. Write a program to add and subtract matrices.

In [6]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


### Q5. Create an n × n matrix where all sub-matrices have even sum of opposite corners.

In [7]:
import numpy as np

n = 4

matrix = np.zeros((n,n), dtype=int)

for i in range(n):
    for j in range(n):
        matrix[i][j] = (i + j) % 2

print(matrix)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


### Q6. Perform row-wise element addition in tuple matrix.

In [8]:
matrix = (
    (1,2,3),
    (4,5,6),
    (7,8,9)
)

row_sum = [sum(row) for row in matrix]

print(row_sum)

[6, 15, 24]
